package paths

const (
	Login                 = "/auth/login"
	Kiosk                 = "/auth/kiosk"
	AllEmployees          = "/employees/all"
	FilterEmployees       = "/employees"
	Upload                = "/file/upload"
	Export                = "/file/export"
	Combinations          = "/combinations"
	Branches              = "/branches"
	Cities                = "/cities"
	Departments           = "/departments"
	Divisions             = "/divisions"
	DocumentAdd           = "/document/create"
	DocumentCreateConfirm = "/document/create/confirm"
	DocumentUpdate        = "/document/update"
	DocumentConfirm       = "/document/confirm"
	DocumentUpdateConfirm = "/document/update/confirm"
	AktualDokument        = "/document/actual"
	EditedDokument        = "/document/edited"
	FilterDokument        = "/document/filter"
	UnsignedSigns         = "/unsigned/signatures"
	SkillMatrix           = "/skill/matrix"
	SignDocument          = "/sign/document"
	SignSuperior          = "/sign/superior"
	SignTraining          = "/sign/training"
	SignedSigns           = "/signed/signatures"
	AllLanguages          = "/languages/all"
	Language              = "/language"
	TrainingUpdateConfirm = "/training/update/confirm"
	TrainingConfirm       = "/training/confirm"
	TrainingSave          = "/training/create"
	TrainingUpdate        = "/training/update"
	CancelsResigns        = "/cancels_resigns"
	EditedTraining        = "/training/edited"
)
