package paths

const (
	Login                 = "/login"
	Kiosk                 = "/kiosk"
	AllEmployees          = "/all_employees"
	Upload                = "/file/upload"
	Export                = "/file/export"
	Comninations          = "/combination"
	Branches              = "/branches"
	Cities                = "/cities"
	Departments           = "/departments"
	Divisions             = "/divisions"
	DocumentAdd           = "/document/create"
	DocumentCreateConfirm = "/document/create/confirm"
	DocumentUpdate        = "/document/update"
	DocumentConfirm       = "/document/confirm"
	DocumentUpdateConfirm = "/document/update/confirm"
	AktualDokument        = "/document/actual"
	EditedDokument        = "/document/edited"
	FilterDokument        = "/document/filter"
	UnsignedSigns         = "/unsigned/signatures"
	SkillMatrix           = "/skill/matrix"
	Sign                  = "/sign"
	SignSuperior          = "/sign/superior"
	SignTraining          = "/sign/training"
	SignedSigns           = "/signed/signatures"
	AllLanguages          = "/languages/all"
	Language              = "/languages/"
	TrainingUpdateConfirm = "/training/update/confirm"
	TrainingConfirm       = "/training/confirm"
	TrainingSave          = "/training/create"
	TrainingUpdate        = "/training/update"
	CancelsResigns        = "/cancels_resigns"
	EditedTraining        = "/training/edited"
)
